async function main() {}

main().catch((err: Error) => {
    console.error(err);
    process.exit(1);
});
